### ISSUE TITLE
Mysql access

### ISSUE THREAD

**Issue by richardmiller** [continuouspipe/remote-environment-client#23]
Does adding a way of accessing a mysql database container make sense? If so should this be done by running the port forwarding?

Is it too specific though, what about things other than mysql, should we try and cover other possibilities as well? If it's just a general port forwarding thing can it just be a generic command?

**Comment by sroze** [comment]
I would love to see a `proxy` command, that _proxies_ to the `kubectl proxy` command :)

**Comment by richardmiller** [comment]
Will the proxy command work for this? Reading the start of this - http://kubernetes.io/docs/user-guide/connecting-to-applications-port-forward/ suggests that proxy is only for http traffic.

**Comment by sroze** [comment]
Oh yes, you're completely right: the port forward is a better option as it's generic!

**Comment by richardmiller** [comment]
closed by #25
