### ISSUE TITLE
Read of configuration variables not correct

### ISSUE THREAD

**Issue by rj-ikos** [continuouspipe/remote-environment-client#36]
When trying to connect to an environment using `cp-remote ssh web` I am experiencing some issues with the settings stored in `.cp-remote-env-settings`

Following the instructions, my project key should be `562bb5d4-afd4-11e6-9479-e74ad44b0268` and my remote branch is `master`. However the connection only works when I use the custom namespace variable. 

Of the 3 scenarios below only [1] works. The documentation suggests the namespace is PROJECT_KEY-REMOTE_BRANCH but this does not appear to be the case based on these examples.

1) Working:

```
REMOTE_BRANCH=master
REMOTE_NAME=origin
PROJECT_KEY=drupal-demo
CUSTOM_NAMESPACE=562bb5d4-afd4-11e6-9479-e74ad44b0268-master
```

2) Not working

```
REMOTE_BRANCH=master
REMOTE_NAME=origin
PROJECT_KEY=562bb5d4-afd4-11e6-9479-e74ad44b0268
```

3) Also not working:

```
REMOTE_BRANCH=master
REMOTE_NAME=origin
PROJECT_KEY=562bb5d4-afd4-11e6-9479-e74ad44b0268
CUSTOM_NAMESPACE=562bb5d4-afd4-11e6-9479-e74ad44b0268-master
```

**Comment by richardmiller** [comment]
This was due to these config values also being used to retrieve the kubernetes configuration. There is now a separate config key used for that which should prevent this issue.
