### ISSUE TITLE
Input validation during setup

### ISSUE THREAD

**Issue by sroze** [continuouspipe/remote-environment-client#65]
In order to prevent unexpected errors, it would be nice to add input validation during the "setup" step. For example, if I answer `https://1.2.3.4` to the question `What is the IP of the cluster?`, it won't fail before the end.

> Unable to connect to the server: dial tcp: lookup https on 8.8.8.8:53: no such host

**Comment by alessandrozucca** [comment]
I've implemented this on the Go version

**Comment by alessandrozucca** [comment]
Closing this ticket as this feature has been implemented.
