### ISSUE TITLE
Request: ability to fetch only specific files

### ISSUE THREAD

**Issue by chicgeek** [continuouspipe/remote-environment-client#66]
`cp-remote fetch` pulls all remote files. It would be useful to have a command to pull only specific files, perhaps as an argument to the existing `fetch` command.

Example:

    cp-remote fetch foo.yml

**Comment by alessandrozucca** [comment]
This has been added on the Go version 0.0.1-beta.3

**Comment by alessandrozucca** [comment]
The Go version is now the official version. 
Closing this ticket as this feature has been implemented.
